services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 9002:8000
    depends_on:
      - db
  grpc:
    build:
      context: .
      dockerfile: Grpc.Dockerfile
    volumes:
      - .:/grpc
    ports:
      - 50051:50051
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./user_service_project/.env
    ports:
      - 5655:5432
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  user_data:
